name: Azure CLI deployment to master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch resources
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish "Eg.rel/Eg.rel.AuthService/Eg.rel.AuthService.csproj" -c Release -o src/Eg.rel

      - name: Create zip archive
        shell: bash
        run: |
          cd src/Eg.rel
          zip -r eg-rel-auth-artifact.zip .
          ls -l
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SP_CREDENTIALS }}

      - name: Azure CLI deployment
        uses: azure/CLI@v1
        with:
          azcliversion: 2.43.0
          inlineScript: |
            ls -l
            cd src/Eg.rel
            az webapp deployment source config-zip --resource-group "eg-rel-rg" --src "eg-rel-auth-artifact.zip" --name "eg-rel-authservice"